In [1]:
#question 1
import numpy as np

In [2]:
new_array=np.array([[1,2,3],[4,5,6]])

In [3]:
l=new_array.tolist()

In [4]:
print(l)

[[1, 2, 3], [4, 5, 6]]


In [5]:
print(new_array)

[[1 2 3]
 [4 5 6]]


In [6]:
#question 2 
import numpy as np
new_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
l=new_array.trace()
print(l)

15


In [7]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
x=2
for i in array:
    if x<i:
        arr=arr+i
print(arr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
#question 3
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print("original array :")
print(array)
print("values bigger than 2 =", array[array>2])

original array :
[[1 2 3]
 [4 5 6]]
values bigger than 2 = [3 4 5 6]


In [9]:
#question 4
import numpy as np
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[2,2,4],[5,6,7]])
ad=np.add(array1,array2)
print(ad)

[[ 3  4  7]
 [ 9 11 13]]


In [27]:
#question 5
import numpy as np
array=np.array([[1,2,3],[4,5,6],])
y=array-array.mean(axis=1, keepdims=True)
print(y)

[[-1.  0.  1.]
 [-1.  0.  1.]]


In [18]:
print(array)

[[1 2 3]
 [4 5 6]]
